---
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - nfs
    - packer-rhel
    - elixir
    - postgresql
    - nodejs
    - git
  tasks:
    - name: set postgres password
      postgresql_user: user=postgres password=postgres
  vars:
    postgresql_version: 9.4
    nodejs_version: 5.x

